name: myapp
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_local_notifications: ^19.4.2
  video_player: ^2.10.0
  provider: ^6.1.5+1
  google_fonts: ^6.3.1
  path_provider: ^2.1.5
  timezone: ^0.10.1
  permission_handler: ^12.0.1
  shared_preferences: ^2.5.3
  audioplayers: ^6.5.1
  android_alarm_manager_plus: ^5.0.0
  awesome_notifications: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/videos/
    - assets/audio/

  fonts:
    - family: BpgNinoMtavruli
      fonts:
        - asset: assets/fonts/bpg_nino_mtavruli_normal.otf
    - family: Eka
      fonts:
        - asset: assets/fonts/eka.ttf
